// NetInfo
export const NETINFO_SET_STATUS = 'NETINFO_SET_STATUS';

// Navigation
export const NAVIGATION_PUSH = 'NAVIGATION_PUSH';
export const NAVIGATION_POP = 'NAVIGATION_POP';
export const NAVIGATION_REPLACE = 'NAVIGATION_REPLACE';
